#!/usr/bin/env bash

QUEST_ROOT="$HOME/Workspace/csm/QuEST"
USER_SOURCE="$HOME/Workspace/csm/QuEST/workspace/qca/qca.c"
OUTPUT_EXE="exe_qca"

bash -c "../utilities/build-tool $QUEST_ROOT $USER_SOURCE $OUTPUT_EXE"
