#!/usr/bin/env bash

QUEST_ROOT="$HOME/Workspace/csm/QuEST"
PRECISION=2
MULTITHREADED=OFF
DISTRIBUTED=OFF
GPUACCELERATED=ON
GPUCOMPUTECAPABILITY=75
USER_SOURCE="$HOME/Workspace/csm/QuEST/workspace/qca/qca.c"
OUTPUT_EXE="exe_qca"

bash -c "../build-utilities/build-tool $QUEST_ROOT \
                                       $PRECISION \
                                       $MULTITHREADED \
                                       $DISTRIBUTED \
                                       $GPUACCELERATED \
                                       $GPUCOMPUTECAPABILITY \
                                       $USER_SOURCE \
                                       $OUTPUT_EXE"
